Feature/#9 adding an issue
CreatekIO/flight_plan pull request #136
Opened 2019-09-17 16:46 UTC by reissjohnson

connects #9 

- Still a bit of a WIP but its at the point where we could ship it for a working add issue feature.

2019-09-17 16:47 UTC, reissjohnson reviewed
Change ordering of adding a new ticket, so they do not get sent to the bottom.

2019-09-20 12:55 UTC, rjpaskin requested changes
Think we need to do something with the prettier config - I think my editor might be using the settings from MyRewards, so maybe we should add those settings and rebase this branch so that we don't get all the changes/conflicts?

2019-09-20 12:55 UTC, rjpaskin commented on app/controllers/api/board_tickets_controller.rb
> +class Api::BoardTicketsController < AuthenticatedController
API controllers are generally for `flight_plan_cli` and use tokens to authenticate - recommend adding the `create` action to the existing `BoardTicketsController` instead?

2019-09-20 12:55 UTC, rjpaskin commented on app/services/ticket_creation_service.rb
> +    BoardRepo.find(@repo_id)
Nit: use the `attr_reader` here?

2019-09-20 12:55 UTC, rjpaskin commented on app/services/ticket_creation_service.rb
> +      )
What do you think about creating the remote ticket first, then using `Ticket.import` to get it into the database? Saves having to update the ticket - and having it in the database in an incomplete state.

2019-09-20 12:55 UTC, rjpaskin commented on app/javascript/action_creators/index.js
> +        dispatch(ticketCreation(response))
Handle error responses and promise rejections?

2019-10-14 16:28 UTC, rjpaskin approved these changes
Subject to reformatting to match existing style (and subsequent PR to get whole codebase formatted the same)

2019-10-14 16:31 UTC, rjpaskin commented
Closed in favour of #142

2019-10-14 16:31 UTC, closed without merging